version: 0.2

phases:
  pre_build:
    commands:
      - npm install --no-progress --silent
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - git submodule init
      - git submodule update --remote --recursive
  build:
    commands:
      - npm run test