version: 0.2

phases:
  pre_build:
    commands:
      - npm install --no-progress --silent
      - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      - git init
      - git remote add origin https://github.com/Gangmin-dev/lambda-testing-practice.git
      - git fetch origin main
      - git checkout -f main
      - git submodule init
      - git submodule update --remote --recursive
  build:
    commands:
      - npm run test