version: '3.1'

services:
  test-db:
    container_name: test-db
    image: mysql:8.0.23
    ports:
      - 3336:3306
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      # - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env


